In [1]:
# Import Dependencies
import pandas as pd
import os

In [3]:
# look for missing values
crimeDF.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [2]:
# Reference the file where the CSV is located
resource = os.path.join("Resources","crime_incident_data2017.csv")
# Import the data into a Pandas DataFrame
crimeRawDF = pd.read_csv(resource)
crimeDF = pd.read_csv(resource)
crimeDF.head(10)

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
5,5400 BLOCK OF NE MALLORY AVE,17-900129,Property,King,1,11/28/10,11/1/10,1612,Fraud Offenses,1,Identity Theft,45.5625,-122.664,7647987.0,698581.0,1/3/17,1/1/17
6,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
7,5000 BLOCK OF NE 19TH AVE,17-901079,Property,Vernon,1,11/8/13,11/1/13,1200,Fraud Offenses,1,Identity Theft,45.5594,-122.646,7652567.0,697337.0,1/26/17,1/1/17
8,12000 BLOCK OF SE PINE ST,17-900253,Property,Hazelwood,1,1/6/14,1/1/14,805,Fraud Offenses,1,Credit Card/ATM Fraud,45.5204,-122.539,7679522.0,682404.0,1/6/17,1/1/17
9,12000 BLOCK OF SE PINE ST,17-900253,Property,Hazelwood,1,1/6/14,1/1/14,805,Fraud Offenses,1,Identity Theft,45.5204,-122.539,7679522.0,682404.0,1/6/17,1/1/17

In [4]:
# drop null rows
crimeDF = crimeDF.dropna(how='any')

In [5]:
# verify counts
crimeDF.count()

Address              36146
Case Number          36146
Crime Against        36146
Neighborhood         36146
Number of Records    36146
Occur Date           36146
Occur Month Year     36146
Occur Time           36146
Offense Category     36146
Offense Count        36146
Offense Type         36146
Open Data Lat        36146
Open Data Lon        36146
Open Data X          36146
Open Data Y          36146
Report Date          36146
Report Month Year    36146
dtype: int64

In [6]:
# Check to see if there are any values with mispelled or similar values in "Offense Type"
crimeDF["Offense Type"].value_counts()

Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       2824
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
Theft From Building                             895
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    145
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     73
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Commercial Sex Acts                               1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [7]:
# Combine similar offenses
crimeDF = crimeDF.replace(
    {'Burglary': 'Burglary','Stolen Property Offenses':'Burglary', 'Theft From Building': 'Burglary'})
crimeDF.columns

Index(['Address', 'Case Number', 'Crime Against', 'Neighborhood',
       'Number of Records', 'Occur Date', 'Occur Month Year', 'Occur Time',
       'Offense Category', 'Offense Count', 'Offense Type', 'Open Data Lat',
       'Open Data Lon', 'Open Data X', 'Open Data Y', 'Report Date',
       'Report Month Year'],
      dtype='object')

In [8]:
# Check to see if you comnbined similar offenses correctly in "Offense Type".
crimeDF["Offense Type"].value_counts()

Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       3776
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    145
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     73
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Commercial Sex Acts                               1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [9]:
# Compare numbers to raw data
crimeRawDF["Offense Type"].value_counts()

Theft From Motor Vehicle                       7256
All Other Larceny                              4900
Motor Vehicle Theft                            4799
Vandalism                                      4189
Burglary                                       2901
Simple Assault                                 2453
Shoplifting                                    2332
Identity Theft                                 2040
Intimidation                                   1678
Aggravated Assault                             1217
Drug/Narcotic Violations                       1142
Theft of Motor Vehicle Parts or Accessories    1107
False Pretenses/Swindle/Confidence Game         972
Theft From Building                             961
Robbery                                         680
Counterfeiting/Forgery                          470
Weapons Law Violations                          298
Credit Card/ATM Fraud                           264
Rape                                            228
Arson                                           221
Prostitution                                    166
Fondling                                        147
Pocket-Picking                                  107
Purse-Snatching                                  98
Embezzlement                                     78
Stolen Property Offenses                         59
Kidnapping/Abduction                             56
Sodomy                                           51
Hacking/Computer Invasion                        22
Theft From Coin-Operated Machine or Device       20
Animal Cruelty                                   19
Statutory Rape                                   18
Murder and Non-negligent Manslaughter            14
Extortion/Blackmail                              13
Assisting or Promoting Prostitution              11
Pornography/Obscene Material                     11
Sexual Assault With An Object                    10
Drug Equipment Violations                         6
Impersonation                                     6
Involuntary Servitude                             4
Wire Fraud                                        4
Commercial Sex Acts                               2
Welfare Fraud                                     1
Incest                                            1
Name: Offense Type, dtype: int64

In [10]:
# Create a new DataFrame that looks into a specific neighborhood
crimeDF["Neighborhood"].value_counts()
downtownCrime = crimeDF.loc[crimeDF["Neighborhood"] == "Downtown",:]
downtownCrime.head()

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
32,500 BLOCK OF SW OAK ST,17-900051,Property,Downtown,1,1/31/16,1/1/16,2300,Larceny Offenses,1,Theft From Motor Vehicle,45.5217,-122.677,7644291.0,683795.0,1/2/17,1/1/17
33,1300 BLOCK OF SW WASHINGTON ST,17-4490,Property,Downtown,1,1/3/16,1/1/16,1900,Motor Vehicle Theft,1,Motor Vehicle Theft,45.5223,-122.685,7642167.0,684106.0,1/5/17,1/1/17
63,1100 BLOCK OF SW 2ND AVE,17-27849,Property,Downtown,1,6/1/16,6/1/16,1,Fraud Offenses,1,Identity Theft,45.5150,-122.676,7644326.0,681371.0,1/28/17,1/1/17
86,1000 BLOCK OF SW JEFFERSON ST,17-900855,Property,Downtown,1,9/28/16,9/1/16,2000,Larceny Offenses,1,All Other Larceny,45.5161,-122.685,7642141.0,681831.0,1/22/17,1/1/17
95,1100 BLOCK OF SW 2ND AVE,17-5712,Property,Downtown,1,10/20/16,10/1/16,1200,Robbery,1,Robbery,45.5150,-122.676,7644326.0,681371.0,1/6/17,1/1/17